global:
  scrape_interval: 5s # Scrapea cada 5 segundos (rápido para demos)
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservicios'
    metrics_path: '/actuator/prometheus' # Spring Boot expone métricas aquí
    static_configs:
      - targets:
          # Aquí listas TODOS tus contenedores de Java + puerto interno
          - 'moduloagregador:8080'
          - 'moduloavd:8081'
          - 'modulodinamica:8082'
          - 'moduloestadisticas:8083'
          - 'moduloestatica:8084'
          - 'modulonormalizador:8085'
          - 'moduloproxy:8086'
          - 'modulopublico:8087'
          - 'moduloauth:9092'
          - 'frontend:8088'